### ISSUE TITLE
setting -Dawt.useSystemAAFontSettings=gasp makes some applications look worse

### ISSUE THREAD

**Issue by mhjacks** [silenc3r/fedora-better-fonts#1]
For example, megamek and freemind (which is in the fedora repos) look worse with gasp than not having the variable set.

Thanks for working on this - the overall web experience on Chrome is loads better with your config enabled.

**Comment by silenc3r** [comment]
You're right. I think the best option is to remove the configuration file completely since it affects only applications launched from terminal and I can't make it look better than default setting.
