### ISSUE TITLE
The repo link is offline

### ISSUE THREAD

**Issue by bkdwt** [silenc3r/fedora-better-fonts#28]
Hi! I tried to install the repo but the link is off:

Curl error (7): Couldn't connect to server for https://copr.fedorainfracloud.org/coprs/dawid/better_fonts/repo/fedora-33/dnf.repo?arch=x86_64 [Failed to connect to copr.fedorainfracloud.org port 443: Conexão recusada]

Thanks! :)

**Comment by silenc3r** [comment]
COPR isn't known for its reliability. Try again.

**Comment by bkdwt** [comment]
> COPR isn't known for its reliability. Try again.

I tested it yesterday and it worked. Thanks!
