### ISSUE TITLE
Better fonts in Silverblue 

### ISSUE THREAD

**Issue by dwestford17** [silenc3r/fedora-better-fonts#35]
Is there a way to apply these changes in Fedora  Silverblue without layering the packages?

**Comment by ghost** [comment]
You can.
`sudo wget -P /etc/yum.repos.d/ https://copr.fedorainfracloud.org/coprs/dawid/better_fonts/repo/fedora-$(rpm -E %fedora)/dawid-better_fonts-fedora-$(rpm -E %fedora).repo`
`sudo rpm-ostree install fontconfig-enhanced-defaults fontconfig-font-replacements`
But right now you have to additionally rely on [this](https://github.com/silenc3r/fedora-better-fonts/issues/37) workaround.

**Comment by martijk** [comment]
> You can. `sudo wget -P /etc/yum.repos.d/ https://copr.fedorainfracloud.org/coprs/dawid/better_fonts/repo/fedora-$(rpm -E %fedora)/dawid-better_fonts-fedora-$(rpm -E %fedora).repo` `sudo rpm-ostree install fontconfig-enhanced-defaults fontconfig-font-replacements` But right now you have to additionally rely on [this](https://github.com/silenc3r/fedora-better-fonts/issues/37) workaround.

I think that @dwestford17 meant without using `rpm-ostree`, so without layering the packages on top of the base installation. That is possible, by copying the fontconfig files to `~/.config/fontconfig/conf.d/` and the fonts to `~/.local/share/fonts/`. I'm using that setup and I've also symlinked `~/.fonts -> ~/.local/share/fonts/` and `~/.fonts.conf.d -> ~/.config/fontconfig/conf.d/`, but that shouldn't be necessary. You might need to execute `dconf write /org/gnome/settings-daemon/plugins/xsettings/antialiasing "'rgba'"` as well.

**Comment by dwestford17** [comment]
Thank you. The suggestions from @martijk work.
