### ISSUE TITLE
Package conflict with texlive-cabin

### ISSUE THREAD

**Issue by makruiten** [silenc3r/fedora-better-fonts#4]
The cabin font conflicts with `texlive-cabin` from the official Fedora repositories, which is included in `texlive-collection-fontsextra`.

```
Error: Transaction check error:
  file /usr/share/fonts/cabin from install of texlive-cabin-6:svn39875-36.fc27.5.noarch conflicts with file from package cabin-fonts-2.001-1.fc27.noarch
```

**Comment by silenc3r** [comment]
The problem is that ```texlive-cabin``` package provides this symlink: ```/usr/share/fonts/cabi
n -> /usr/share/texlive/texmf-dist/fonts/opentype/impallari/cabin```.  
I've analysed other texlive font packages and it seems they use these kind of symlinks only for fonts that aren't available in official repository. For example ```texlive-dejavu``` or ```texlive-roboto``` do not have symlinks like that.

I'm not sure what to do about it but I guess the safest option would be to remove ```cabin-fonts``` from my repository and use ```texlive-cabin``` instead.

**Comment by makruiten** [comment]
That sounds like a workable solution. It's now impossible to install texlive-collection-fontsextra. Although I get that it might be less than ideal to depend on a package that installs a symlinked font.

**Comment by makruiten** [comment]
For future visitors: for now you can `rpm -e --nodeps cabin-fonts` to remove the Cabin fonts without removing the fontconfig packages and then install `texlive-collection-fontsextra` or `texlive-cabin`, until this issue is resolved. It's a workaround and not a solution.

**Comment by oxapentane** [comment]
> might be less than ideal to depend on a package that installs a symlinked font.

Well, maybe It is possible to rename font shipped by this repo to something like "gfont-cabin", so there will be no conflict with the symlink. Though I don't know how It will behave, basically there will be two fonts with identical font family string (which is how the substitution works, as far as I understand).

Also, thanks for the workaround, but I'm not sure how this will play out when packages from this repo will try to update.

**Comment by silenc3r** [comment]
I think I'll just remove ```cabin-fonts``` from repo and use Lato as Gill Sans replacement.

**Comment by makruiten** [comment]
Sounds good to me. It's close enough.
