### ISSUE TITLE
Color fringing with low contrast text

### ISSUE THREAD

**Issue by makruiten** [silenc3r/fedora-better-fonts#5]
I can try to explain it, but I think a screenshot is better (note the light gray text at full resolution):

![ugly-antialiasing](https://user-images.githubusercontent.com/6661233/31768629-7835229e-b4d0-11e7-8bc2-b8312cd63e58.png)

This does not happen in Ubuntu 17.10. I'm aware that this is probably not due to your settings, but maybe you know what's going on here. I don't see where Ubuntu's and your settings differ. Probably something related to the lcd filter. It might be worthwhile to copy Ubuntu's settings, if possible. I checked and it's definitely not related to the different fonts in Ubuntu. The Ubuntu fonts turn out even worse than Cantarell on Fedora:

![ugly-antialiasing2](https://user-images.githubusercontent.com/6661233/31768817-3fe99fae-b4d1-11e7-893e-d2f31e22aa2b.png)

This is Ubuntu's antialiasing:

![nice-antialiasing](https://user-images.githubusercontent.com/6661233/31769177-bba86f52-b4d2-11e7-8c6c-c89439f878e5.png)

**Comment by silenc3r** [comment]
Is it still the issue? I've just tested this on fresh Fedora 27 install in VM and it seems to look OK
![extensions_cantarell](https://user-images.githubusercontent.com/442039/35122669-dce8d8fe-fc9f-11e7-950f-e9feefe7b512.png)

**Comment by makruiten** [comment]
For me the issue is still there, but your screenshot looks absolutely fine, so it might be due to some old settings in some configuration file.

**Comment by selfhostedfun** [comment]
fontconfig is greek to me so I can't tell you why this works, but after doing clean installs on a few machines this week I noticed that if I opened had opened gnome-tweaks prior to installing this copr I had the fringing issue. If I installed the copr and then checked the fonts, I had no issue. 

And just to make sure I wasn't crazy I even reinstalled on my XPS 9360 twice just to verify this was going on. Open gnome-tweaks and go to fonts first? Fringing issue. Install your copr? No fringing.

**Comment by rbu** [comment]
I think I have a different, but similar issue. It basically looks like @silenc3r's screen shot. There's a colored anti-aliasing around black text, but no colors around grey text. However, I'd like only greyscale anti-aliasing.
I did not have this issue before installing the fonts and I don't have the issue in a Fedora 29 Live system.

Setting the Anti-Aliasing in Tweaks->Fonts to greyscale or Subpixel makes *no* difference.

![image](https://user-images.githubusercontent.com/65913/49973629-28a4b580-ff36-11e8-9bc1-516ca7225965.png)

**Comment by makruiten** [comment]
@rbu, subpixel antialiasing is enabled in `/etc/fonts/conf.d/19-enhanced-defaults.conf`, which is provided by this COPR repo.You should be able to restore the original behavior by removing the package: `dnf remove fontconfig-enhanced-defaults`.

**Comment by makruiten** [comment]
@selfhostedfun, that's very interesting. I just checked, and it looks fine now on my Fedora 29 installation. I believe Fedora 29 ships with subpixel antialiasing enabled in the default fontconfig package, while before it was provided by RPMFusion. Did you do clean installs of Fedora 29, or an earlier version?
